### ISSUE TITLE
日本語 translation

### ISSUE THREAD

**Issue by sI1vre** [LeadRDRK/AvatarCropper#1]
more of a test of my japanese skills than anything lmao

[langs.json](https://github.com/LeadRDRK/AvatarCropper/files/13197150/langs.json)
[ja-jpn.json](https://github.com/LeadRDRK/AvatarCropper/files/13197151/ja-jpn.json)

**Comment by LeadRDRK** [comment]
Questionable translation. Some of the strings are too long and don't fit into the layout, and while I can't exactly verify if the translation is accurate or not, through the use of DeepL, I think that most of the translation feels very off.

Closing as rejected for now.
